$axure.loadCurrentPage({
  "url":"p8_6_5学校.html",
  "generationDate":new Date(1438911585007.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"8c7449e873ee4338967edf6156480d7c",
    "type":"Axure:Page",
    "name":"p8_6_5学校",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7326bef055464f2ea98d0570b6391d90",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d062120fb0a24c96a52ddff7f0766d69"},
{
          "id":"c4f997658d834228af93f20a8f87758b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":166},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"841cfbfb246747359b18d4351d592004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":166},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/p8_6_1昵称/u5.png"}},
{
          "id":"28e0c78160474d4694bce29711e15024",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":182,
              "y":167},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51566d29526646ddaee4c85b281c8e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":182,
                  "y":167},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3878d30b2f12463d8b39ed6923f5171d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":323,
              "y":168},
            "size":{
              "width":27,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25a213949a824495ac9a8e1ef28a1b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":323,
                  "y":168},
                "size":{
                  "width":27,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/p8_2_1签到拍照/u4.png"}},
{
          "id":"9faebbf080c048c0912679939caba98c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "hint":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":40,
              "y":204},
            "size":{
              "width":320,
              "height":32}},
          "adaptiveStyles":{
},
          "placeholderText":"输入学校名称"},
{
          "id":"3c918fd4066440ff8ff53ebda525218a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":130},
            "size":{
              "width":330,
              "height":561}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06b1cc3284e448c2b6106814901af537",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":130},
                "size":{
                  "width":330,
                  "height":561}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p8_6_5学校/u12.png"}}]}},
  "masters":{
    "d062120fb0a24c96a52ddff7f0766d69":{
      "packageId":"d062120fb0a24c96a52ddff7f0766d69",
      "type":"Axure:Master",
      "name":"底框",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28ecc4fbd8384e4685c9472eeaea4bf2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":394,
                "height":834},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d603652be6b14b75bd8ad8334dcfe91e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":394,
                    "height":834},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p1启动页/u1.png"}},
{
            "id":"228018ab1eb343b6bcb0319dde7e9659",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"18px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3399FF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":31,
                "y":153},
              "size":{
                "width":335,
                "height":47},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"308d9e591f4147e48dc8d00d30d20966",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3399FF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":31,
                    "y":153},
                  "size":{
                    "width":335,
                    "height":47},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p1启动页/u3.png"}}]}}},
  "objectPaths":{
    "7326bef055464f2ea98d0570b6391d90":{
      "scriptId":"u0",
      "28ecc4fbd8384e4685c9472eeaea4bf2":{
        "scriptId":"u1"},
      "d603652be6b14b75bd8ad8334dcfe91e":{
        "scriptId":"u2"},
      "228018ab1eb343b6bcb0319dde7e9659":{
        "scriptId":"u3"},
      "308d9e591f4147e48dc8d00d30d20966":{
        "scriptId":"u4"}},
    "c4f997658d834228af93f20a8f87758b":{
      "scriptId":"u5"},
    "841cfbfb246747359b18d4351d592004":{
      "scriptId":"u6"},
    "28e0c78160474d4694bce29711e15024":{
      "scriptId":"u7"},
    "51566d29526646ddaee4c85b281c8e4d":{
      "scriptId":"u8"},
    "3878d30b2f12463d8b39ed6923f5171d":{
      "scriptId":"u9"},
    "25a213949a824495ac9a8e1ef28a1b91":{
      "scriptId":"u10"},
    "9faebbf080c048c0912679939caba98c":{
      "scriptId":"u11"},
    "3c918fd4066440ff8ff53ebda525218a":{
      "scriptId":"u12"},
    "06b1cc3284e448c2b6106814901af537":{
      "scriptId":"u13"}}});