$axure.loadCurrentPage({
  "url":"p3-4-2-1____.html",
  "generationDate":new Date(1438911659761.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"af3b989ca9b549c1aec2d526bb89777a",
    "type":"Axure:Page",
    "name":"p3-4-2-1工作地点",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aaf0878a7acf4bd3857ecd0565a07a0f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"53a5a662415045d485c12d8c9170e61f"},
{
          "id":"8b523d8f50834c8e83992049bf24542c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":166}},
          "adaptiveStyles":{
},
          "masterId":"a98f4cc5246e4fe9b021c2e5bafc607c"},
{
          "id":"ea6fee82ba95408fb045e5d8c2e92884",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":160,
              "y":167},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcbdf6c2a6c84be98006ac7829f72e6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":160,
                  "y":167},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a30cda6dc304bfeb793914fd8cefcbc",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":200},
            "size":{
              "width":323,
              "height":510}},
          "adaptiveStyles":{
}},
{
          "id":"098c89ef97bc497ba48b93854c185e03",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":37,
              "y":218},
            "size":{
              "width":323,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"输入面试地点"},
{
          "id":"01f54eb85f004a6fa60c6c3425cfe311",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "verticalAlignment":"top",
            "location":{
              "x":130,
              "y":392},
            "size":{
              "width":150,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c0b2b4e13c74bc7845933a32466fd4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"top",
                "location":{
                  "x":130,
                  "y":392},
                "size":{
                  "width":150,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p2-1-5____/u13.png"}},
{
          "id":"6289c59bba574e32bd135646dfb94ee0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":168},
            "size":{
              "width":27,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faa4d6f3bcca43c0b761e7dd4cad3226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":168},
                "size":{
                  "width":27,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p2-1-1____/u9.png"}},
{
          "id":"98033cea7afd405b84b7a911334e89d5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":130},
            "size":{
              "width":364,
              "height":646}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eef62c64f5a742d89301b4b12dd04bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":130},
                "size":{
                  "width":364,
                  "height":646}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-4-2-1____/u16.jpg"}}]}},
  "masters":{
    "53a5a662415045d485c12d8c9170e61f":{
      "packageId":"53a5a662415045d485c12d8c9170e61f",
      "type":"Axure:Master",
      "name":"底框",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28ecc4fbd8384e4685c9472eeaea4bf2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "size":{
                "width":394,
                "height":834},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d603652be6b14b75bd8ad8334dcfe91e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "size":{
                    "width":394,
                    "height":834},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p0-1启动页/u1.png"}},
{
            "id":"228018ab1eb343b6bcb0319dde7e9659",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3399FF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":31,
                "y":153},
              "size":{
                "width":335,
                "height":47},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"308d9e591f4147e48dc8d00d30d20966",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3399FF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":31,
                    "y":153},
                  "size":{
                    "width":335,
                    "height":47},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p0-1启动页/u3.png"}}]}},
    "a98f4cc5246e4fe9b021c2e5bafc607c":{
      "packageId":"a98f4cc5246e4fe9b021c2e5bafc607c",
      "type":"Axure:Master",
      "name":"返回",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1a9e11f1e9e34429b6dd9555055766a1",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":24,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e89edbbe2aca4fdab060d2bee65b60c2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":24,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p1登录/u16.png"}}]}}},
  "objectPaths":{
    "aaf0878a7acf4bd3857ecd0565a07a0f":{
      "scriptId":"u0",
      "28ecc4fbd8384e4685c9472eeaea4bf2":{
        "scriptId":"u1"},
      "d603652be6b14b75bd8ad8334dcfe91e":{
        "scriptId":"u2"},
      "228018ab1eb343b6bcb0319dde7e9659":{
        "scriptId":"u3"},
      "308d9e591f4147e48dc8d00d30d20966":{
        "scriptId":"u4"}},
    "8b523d8f50834c8e83992049bf24542c":{
      "scriptId":"u5",
      "1a9e11f1e9e34429b6dd9555055766a1":{
        "scriptId":"u6"},
      "e89edbbe2aca4fdab060d2bee65b60c2":{
        "scriptId":"u7"}},
    "ea6fee82ba95408fb045e5d8c2e92884":{
      "scriptId":"u8"},
    "fcbdf6c2a6c84be98006ac7829f72e6c":{
      "scriptId":"u9"},
    "5a30cda6dc304bfeb793914fd8cefcbc":{
      "scriptId":"u10"},
    "098c89ef97bc497ba48b93854c185e03":{
      "scriptId":"u11"},
    "01f54eb85f004a6fa60c6c3425cfe311":{
      "scriptId":"u12"},
    "0c0b2b4e13c74bc7845933a32466fd4a":{
      "scriptId":"u13"},
    "6289c59bba574e32bd135646dfb94ee0":{
      "scriptId":"u14"},
    "faa4d6f3bcca43c0b761e7dd4cad3226":{
      "scriptId":"u15"},
    "98033cea7afd405b84b7a911334e89d5":{
      "scriptId":"u16"},
    "eef62c64f5a742d89301b4b12dd04bf4":{
      "scriptId":"u17"}}});