$axure.loadCurrentPage({
  "url":"p8_9_1修改密码.html",
  "generationDate":new Date(1438911584784.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"yz_msg"],
  "page":{
    "packageId":"c582ddf45734492aa3bd71f4868c5e8d",
    "type":"Axure:Page",
    "name":"p8_9_1修改密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"86e72ad2766447c08ba4644a26c39418",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"d062120fb0a24c96a52ddff7f0766d69"},
{
          "id":"fb6285010abe4108a4715ee02644cccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"21px",
            "location":{
              "x":152,
              "y":170},
            "size":{
              "width":91,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a635eafcb54942259573f72e7aa4f789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"21px",
                "location":{
                  "x":152,
                  "y":170},
                "size":{
                  "width":91,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fabbe71e28264c2f80a9798a8a9ef833",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":52,
              "y":365},
            "size":{
              "width":139,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"71f0e4be05a243b190be6d6a5dfcf59f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":201,
              "y":363},
            "size":{
              "width":131,
              "height":47},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac11389c6d3f43d784adbc6067f86607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":201,
                  "y":363},
                "size":{
                  "width":131,
                  "height":47},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3_1验证手机/u9.png"}},
{
          "id":"10c8ece81c4b4cfbad6f550b04e5fd1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":49,
              "y":414},
            "size":{
              "width":280,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9eee17ccdd9461da56743d1184e9f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":414},
                "size":{
                  "width":280,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ea281bda0994ffc8344f16e61ec1047",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":52,
              "y":520},
            "size":{
              "width":280,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1caebeddf984f26bbae834602334335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":52,
                  "y":520},
                "size":{
                  "width":280,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 p8_9_1_1设置密码",
                      "target":{
                        "targetType":"page",
                        "url":"p8_9_1_1设置密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/p3_1验证手机/u13.png"}},
{
          "id":"b362171b0e9a4d19a5d31c82a05f8b29",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":49,
              "y":265},
            "size":{
              "width":280,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"a4f619c98b264136b2b4cae768253d68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":49,
              "y":240},
            "size":{
              "width":68,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e0e69d4a5cf4aa7b8389b87d3ec5c95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":49,
                  "y":240},
                "size":{
                  "width":68,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e89b84ab6d54e32b8baeeb638dbff7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":52,
              "y":341},
            "size":{
              "width":119,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"271dc7380dea4726854babed771e5181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":341},
                "size":{
                  "width":119,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4b1f41194284056b5cca39af4fb990f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":440,
              "y":200},
            "size":{
              "width":260,
              "height":134},
            "cornerRadiusTopLeft":"16"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1531f58667224edaabcd8ff2c9358395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":440,
                  "y":200},
                "size":{
                  "width":260,
                  "height":134},
                "cornerRadiusTopLeft":"16"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3登录/u21.png"}},
{
          "id":"2306f3626e334d84afbb4788b98f096c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":284},
            "size":{
              "width":260,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/p3登录/u23_line.png"}},
{
          "id":"6d8bff5d820142b1a75745a20bcb3e43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":550,
              "y":214},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7b11a7e579546699f4cdb174ef033f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":550,
                  "y":214},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bceddf3a4844bd58cd2a3fb3b52bf01",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":528,
              "y":248},
            "size":{
              "width":164,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"712159228fe2456cb53db8a1663f3f65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":528,
                  "y":248},
                "size":{
                  "width":164,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea8ffc03929f4542b9d0c60905c75a51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":551,
              "y":304},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f2a4a4119d5459b8117b89cee2ba22c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":551,
                  "y":304},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82c54bc4f69d45578ac1dd7933a8ee38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":47,
              "y":168},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e92fe634b71442998e9f54b75bb5186",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":47,
                  "y":168},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/p8_0实名认证/u43.png"}},
{
          "id":"95421df376ae4794a8803e895f1f38ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":350},
            "size":{
              "width":330,
              "height":561}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abe19841ecb9472f9f2b047196631798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":350},
                "size":{
                  "width":330,
                  "height":561}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p8_9_1修改密码/u30.png"}}]}},
  "masters":{
    "d062120fb0a24c96a52ddff7f0766d69":{
      "packageId":"d062120fb0a24c96a52ddff7f0766d69",
      "type":"Axure:Master",
      "name":"底框",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28ecc4fbd8384e4685c9472eeaea4bf2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "size":{
                "width":394,
                "height":834},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d603652be6b14b75bd8ad8334dcfe91e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "size":{
                    "width":394,
                    "height":834},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p1启动页/u1.png"}},
{
            "id":"228018ab1eb343b6bcb0319dde7e9659",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"18px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3399FF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":31,
                "y":153},
              "size":{
                "width":335,
                "height":47},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"308d9e591f4147e48dc8d00d30d20966",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3399FF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":31,
                    "y":153},
                  "size":{
                    "width":335,
                    "height":47},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p1启动页/u3.png"}}]}}},
  "objectPaths":{
    "86e72ad2766447c08ba4644a26c39418":{
      "scriptId":"u0",
      "28ecc4fbd8384e4685c9472eeaea4bf2":{
        "scriptId":"u1"},
      "d603652be6b14b75bd8ad8334dcfe91e":{
        "scriptId":"u2"},
      "228018ab1eb343b6bcb0319dde7e9659":{
        "scriptId":"u3"},
      "308d9e591f4147e48dc8d00d30d20966":{
        "scriptId":"u4"}},
    "fb6285010abe4108a4715ee02644cccb":{
      "scriptId":"u5"},
    "a635eafcb54942259573f72e7aa4f789":{
      "scriptId":"u6"},
    "fabbe71e28264c2f80a9798a8a9ef833":{
      "scriptId":"u7"},
    "71f0e4be05a243b190be6d6a5dfcf59f":{
      "scriptId":"u8"},
    "ac11389c6d3f43d784adbc6067f86607":{
      "scriptId":"u9"},
    "10c8ece81c4b4cfbad6f550b04e5fd1c":{
      "scriptId":"u10"},
    "e9eee17ccdd9461da56743d1184e9f24":{
      "scriptId":"u11"},
    "7ea281bda0994ffc8344f16e61ec1047":{
      "scriptId":"u12"},
    "b1caebeddf984f26bbae834602334335":{
      "scriptId":"u13"},
    "b362171b0e9a4d19a5d31c82a05f8b29":{
      "scriptId":"u14"},
    "a4f619c98b264136b2b4cae768253d68":{
      "scriptId":"u15"},
    "7e0e69d4a5cf4aa7b8389b87d3ec5c95":{
      "scriptId":"u16"},
    "9e89b84ab6d54e32b8baeeb638dbff7b":{
      "scriptId":"u17"},
    "271dc7380dea4726854babed771e5181":{
      "scriptId":"u18"},
    "c4b1f41194284056b5cca39af4fb990f":{
      "scriptId":"u19"},
    "1531f58667224edaabcd8ff2c9358395":{
      "scriptId":"u20"},
    "2306f3626e334d84afbb4788b98f096c":{
      "scriptId":"u21"},
    "6d8bff5d820142b1a75745a20bcb3e43":{
      "scriptId":"u22"},
    "f7b11a7e579546699f4cdb174ef033f4":{
      "scriptId":"u23"},
    "3bceddf3a4844bd58cd2a3fb3b52bf01":{
      "scriptId":"u24"},
    "712159228fe2456cb53db8a1663f3f65":{
      "scriptId":"u25"},
    "ea8ffc03929f4542b9d0c60905c75a51":{
      "scriptId":"u26"},
    "5f2a4a4119d5459b8117b89cee2ba22c":{
      "scriptId":"u27"},
    "82c54bc4f69d45578ac1dd7933a8ee38":{
      "scriptId":"u28"},
    "9e92fe634b71442998e9f54b75bb5186":{
      "scriptId":"u29"},
    "95421df376ae4794a8803e895f1f38ed":{
      "scriptId":"u30"},
    "abe19841ecb9472f9f2b047196631798":{
      "scriptId":"u31"}}});