$axure.loadCurrentPage({
  "url":"p2-1-3____.html",
  "generationDate":new Date(1438911658082.03),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"503d48e5feaf4077a8ad8e594e7691d2",
    "type":"Axure:Page",
    "name":"p2-1-3招聘人数",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a3959651ed5a463fbaaa4e2807fe3e39",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"53a5a662415045d485c12d8c9170e61f"},
{
          "id":"8cddace0ae674cf99c61e2bd7b866948",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":166},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84eb979a8d3f4b87a0f62735d9ac5c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":166},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 p2-1我的发布_新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"p2-1我的发布_新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/p1登录/u16.png"}},
{
          "id":"cd723e71b7d8485c80a9a129d4599e63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":160,
              "y":168},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca1f3470b6104a368e81baa37c331347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":160,
                  "y":168},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6458569007f4e98b8def775433b2f45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":323,
              "y":168},
            "size":{
              "width":27,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2fd64ee5d48429393b52fd1b6fff130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":323,
                  "y":168},
                "size":{
                  "width":27,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 p2-1我的发布_新增/编辑",
                      "target":{
                        "targetType":"page",
                        "url":"p2-1我的发布_新增_编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/p2-1-1____/u9.png"}},
{
          "id":"c19faf40db95444792307db627b44214",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1}}},
            "location":{
              "x":38,
              "y":204},
            "size":{
              "width":320,
              "height":32}},
          "adaptiveStyles":{
},
          "placeholderText":"输入招聘人数"},
{
          "id":"cc090ab4ac5c496e84898af6ab924e20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":130},
            "size":{
              "width":364,
              "height":646}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30d763e99b4b40158622a868a3fbee5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":130},
                "size":{
                  "width":364,
                  "height":646}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p2-1-3____/u12.png"}}]}},
  "masters":{
    "53a5a662415045d485c12d8c9170e61f":{
      "packageId":"53a5a662415045d485c12d8c9170e61f",
      "type":"Axure:Master",
      "name":"底框",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28ecc4fbd8384e4685c9472eeaea4bf2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "size":{
                "width":394,
                "height":834},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d603652be6b14b75bd8ad8334dcfe91e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "size":{
                    "width":394,
                    "height":834},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p0-1启动页/u1.png"}},
{
            "id":"228018ab1eb343b6bcb0319dde7e9659",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3399FF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":31,
                "y":153},
              "size":{
                "width":335,
                "height":47},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"308d9e591f4147e48dc8d00d30d20966",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3399FF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":31,
                    "y":153},
                  "size":{
                    "width":335,
                    "height":47},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p0-1启动页/u3.png"}}]}}},
  "objectPaths":{
    "a3959651ed5a463fbaaa4e2807fe3e39":{
      "scriptId":"u0",
      "28ecc4fbd8384e4685c9472eeaea4bf2":{
        "scriptId":"u1"},
      "d603652be6b14b75bd8ad8334dcfe91e":{
        "scriptId":"u2"},
      "228018ab1eb343b6bcb0319dde7e9659":{
        "scriptId":"u3"},
      "308d9e591f4147e48dc8d00d30d20966":{
        "scriptId":"u4"}},
    "8cddace0ae674cf99c61e2bd7b866948":{
      "scriptId":"u5"},
    "84eb979a8d3f4b87a0f62735d9ac5c9b":{
      "scriptId":"u6"},
    "cd723e71b7d8485c80a9a129d4599e63":{
      "scriptId":"u7"},
    "ca1f3470b6104a368e81baa37c331347":{
      "scriptId":"u8"},
    "e6458569007f4e98b8def775433b2f45":{
      "scriptId":"u9"},
    "f2fd64ee5d48429393b52fd1b6fff130":{
      "scriptId":"u10"},
    "c19faf40db95444792307db627b44214":{
      "scriptId":"u11"},
    "cc090ab4ac5c496e84898af6ab924e20":{
      "scriptId":"u12"},
    "30d763e99b4b40158622a868a3fbee5b":{
      "scriptId":"u13"}}});