$axure.loadCurrentPage({
  "url":"p3-1-1-1____.html",
  "generationDate":new Date(1438911660878.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6bab1835b70e479993e5c507675d598b",
    "type":"Axure:Page",
    "name":"p3-1-1-1添加结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"920fa116dc914482a0b59bef581787d8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"53a5a662415045d485c12d8c9170e61f"},
{
          "id":"bd70e4be7bf0436bb82823ed6e7375c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":164,
              "y":166},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c39c0a6efa4115a9206216613b12de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":164,
                  "y":166},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16cf5c5a18d64dcf8d239811c1058dac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":37,
              "y":670},
            "size":{
              "width":320,
              "height":40},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5d9f14540c948fabb219ea8737c34c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":37,
                  "y":670},
                "size":{
                  "width":320,
                  "height":40},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p1登录/u18.png"}},
{
          "id":"cf772bdfc3fa424d97b31ba387700f50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":209},
            "size":{
              "width":319,
              "height":72},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ec89d357e0d4de5a5d184d5380969dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":209},
                "size":{
                  "width":319,
                  "height":72},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-1报名列表/u9.png"}},
{
          "id":"2fa5685d67fd4991869b0ff01bd18cc2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":220},
            "size":{
              "width":50,
              "height":50},
            "borderWidth":"1",
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1039960d4e1041babddf3e53534f6ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":220},
                "size":{
                  "width":50,
                  "height":50},
                "borderWidth":"1",
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-1报名列表/u15.png"}},
{
          "id":"fee768f922934155a1a5c0c3e9343d96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":218},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"815215a3e08240d4a4138ee60d51acc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":218},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea0064f9280841c2b3dd4ba1abd29e49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF66CC},
            "location":{
              "x":148,
              "y":217},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b87bba145964419a9c84f5eb34af368f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF66CC},
                "location":{
                  "x":148,
                  "y":217},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-1报名列表/u19.png"}},
{
          "id":"d01564d1393a4b72b6bc9626197800a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":244},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"795c27fec1754224bfed722ab467a5fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":244},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"505bf8c25e8e4933b30c8b79b0d89ea3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6666FF},
            "location":{
              "x":198,
              "y":217},
            "size":{
              "width":63,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4487be7644a140788dd452bb9dbee1ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6666FF},
                "location":{
                  "x":198,
                  "y":217},
                "size":{
                  "width":63,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-1报名列表/u23.png"}},
{
          "id":"53c9a4a879ce4b98b3be79db58edfebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":244},
            "size":{
              "width":91,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edfeef52f93347e8b192a49dd75cb99f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":244},
                "size":{
                  "width":91,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61d425d309f541c1abaa638c63887f2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":291},
            "size":{
              "width":319,
              "height":72},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15f33fb4a4dc41e88ae5d256797bb16e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":291},
                "size":{
                  "width":319,
                  "height":72},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-1报名列表/u9.png"}},
{
          "id":"85fdcc6fd2a94c188ee4176037d39475",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":166},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a68d574beddf4f94b0de762f7f404b48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":166},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p1登录/u16.png"}},
{
          "id":"0cbb0b5a9e8a4294859515f978e1dc7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":427,
              "y":158},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21cf9df5b7a345b3ae3e71636b88f9a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":427,
                  "y":158},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d55847e2fe904104afa7a1c2f1d0e3a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":158},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0be35faa7599413e88ef0755d461fb84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":158},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00e025f0ad094d5fb81bb47dcdd55c25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":427,
              "y":200},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a571d90ac214715990434c12a9bfc2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":427,
                  "y":200},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a0e3406259d4faeb295eb2cecb4be6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":518,
              "y":200},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b510aef3fe024331bc2f57894b7ba964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":518,
                  "y":200},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5e1995563c046a790db11a51339c821",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":226},
            "size":{
              "width":364,
              "height":646}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8262e5df91424a9db9b13e070e573246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":226},
                "size":{
                  "width":364,
                  "height":646}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/p3-1-1-1____/u35.png"}}]}},
  "masters":{
    "53a5a662415045d485c12d8c9170e61f":{
      "packageId":"53a5a662415045d485c12d8c9170e61f",
      "type":"Axure:Master",
      "name":"底框",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"28ecc4fbd8384e4685c9472eeaea4bf2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "size":{
                "width":394,
                "height":834},
              "rotation":"0",
              "textRotation":"0",
              "borderWidth":"0",
              "cornerRadiusTopLeft":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d603652be6b14b75bd8ad8334dcfe91e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "size":{
                    "width":394,
                    "height":834},
                  "rotation":"0",
                  "textRotation":"0",
                  "borderWidth":"0",
                  "cornerRadiusTopLeft":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p0-1启动页/u1.png"}},
{
            "id":"228018ab1eb343b6bcb0319dde7e9659",
            "label":"",
            "type":"flowShape",
            "styleType":"flowShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontSize":"18px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3399FF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFE4E4E4},
              "location":{
                "x":31,
                "y":153},
              "size":{
                "width":335,
                "height":47},
              "borderFill":{
                "fillType":"solid",
                "color":0x797979}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"308d9e591f4147e48dc8d00d30d20966",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontSize":"18px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3399FF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4},
                  "location":{
                    "x":31,
                    "y":153},
                  "size":{
                    "width":335,
                    "height":47},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0x797979}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/p0-1启动页/u3.png"}}]}}},
  "objectPaths":{
    "920fa116dc914482a0b59bef581787d8":{
      "scriptId":"u0",
      "28ecc4fbd8384e4685c9472eeaea4bf2":{
        "scriptId":"u1"},
      "d603652be6b14b75bd8ad8334dcfe91e":{
        "scriptId":"u2"},
      "228018ab1eb343b6bcb0319dde7e9659":{
        "scriptId":"u3"},
      "308d9e591f4147e48dc8d00d30d20966":{
        "scriptId":"u4"}},
    "bd70e4be7bf0436bb82823ed6e7375c2":{
      "scriptId":"u5"},
    "61c39c0a6efa4115a9206216613b12de":{
      "scriptId":"u6"},
    "16cf5c5a18d64dcf8d239811c1058dac":{
      "scriptId":"u7"},
    "c5d9f14540c948fabb219ea8737c34c6":{
      "scriptId":"u8"},
    "cf772bdfc3fa424d97b31ba387700f50":{
      "scriptId":"u9"},
    "4ec89d357e0d4de5a5d184d5380969dd":{
      "scriptId":"u10"},
    "2fa5685d67fd4991869b0ff01bd18cc2":{
      "scriptId":"u11"},
    "1039960d4e1041babddf3e53534f6ddc":{
      "scriptId":"u12"},
    "fee768f922934155a1a5c0c3e9343d96":{
      "scriptId":"u13"},
    "815215a3e08240d4a4138ee60d51acc9":{
      "scriptId":"u14"},
    "ea0064f9280841c2b3dd4ba1abd29e49":{
      "scriptId":"u15"},
    "b87bba145964419a9c84f5eb34af368f":{
      "scriptId":"u16"},
    "d01564d1393a4b72b6bc9626197800a9":{
      "scriptId":"u17"},
    "795c27fec1754224bfed722ab467a5fb":{
      "scriptId":"u18"},
    "505bf8c25e8e4933b30c8b79b0d89ea3":{
      "scriptId":"u19"},
    "4487be7644a140788dd452bb9dbee1ff":{
      "scriptId":"u20"},
    "53c9a4a879ce4b98b3be79db58edfebc":{
      "scriptId":"u21"},
    "edfeef52f93347e8b192a49dd75cb99f":{
      "scriptId":"u22"},
    "61d425d309f541c1abaa638c63887f2a":{
      "scriptId":"u23"},
    "15f33fb4a4dc41e88ae5d256797bb16e":{
      "scriptId":"u24"},
    "85fdcc6fd2a94c188ee4176037d39475":{
      "scriptId":"u25"},
    "a68d574beddf4f94b0de762f7f404b48":{
      "scriptId":"u26"},
    "0cbb0b5a9e8a4294859515f978e1dc7b":{
      "scriptId":"u27"},
    "21cf9df5b7a345b3ae3e71636b88f9a1":{
      "scriptId":"u28"},
    "d55847e2fe904104afa7a1c2f1d0e3a2":{
      "scriptId":"u29"},
    "0be35faa7599413e88ef0755d461fb84":{
      "scriptId":"u30"},
    "00e025f0ad094d5fb81bb47dcdd55c25":{
      "scriptId":"u31"},
    "7a571d90ac214715990434c12a9bfc2e":{
      "scriptId":"u32"},
    "2a0e3406259d4faeb295eb2cecb4be6b":{
      "scriptId":"u33"},
    "b510aef3fe024331bc2f57894b7ba964":{
      "scriptId":"u34"},
    "b5e1995563c046a790db11a51339c821":{
      "scriptId":"u35"},
    "8262e5df91424a9db9b13e070e573246":{
      "scriptId":"u36"}}});